image: "maven:3-openjdk-11"

before_script:
  - echo $CI_COMMIT_BRANCH

stages:
  - build
  - release
  - deploy

build:
  stage: build
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/auth-0.0.1-SNAPSHOT.jar

tests:
  stage: build
  script:
    - mvn test

dev-image-creation:
  image: docker:git
  stage: release
  services:
    - docker:dind
  before_script:
    - docker ps
  script:
    # Non interactive ssh gracefully reloads server
    - ls
    - docker login -u $CI_REGISTRY_USER -p $DOCKER_CI_TOKEN registry.gitlab.com #logs into gitlab docker registery, make sure to have this variables defined
    - docker build -t $IMAGE_NAME:develop . # creates a docker image
    - docker push $IMAGE_NAME:develop # pushes the create docker image to docker registry
  dependencies:
    - build
  only:
    - develop

releasedImage:
  image: docker:git
  stage: release
  services:
    - docker:dind
  before_script:
    - docker ps
  script:
    # Non interactive ssh gracefully reloads server
    - ls
    - docker login -u $CI_REGISTRY_USER -p $DOCKER_CI_TOKEN registry.gitlab.com #logs into gitlab docker registery, make sure to have this variables defined
    - docker build -t $IMAGE_NAME . # creates a docker image
    - docker push $IMAGE_NAME:latest # pushes the create docker image to docker registry
  dependencies:
    - build
  only:
    - master